### ISSUE TITLE
Profile Pictures not showing

### ISSUE THREAD

**Issue by kendalldTalon** [YannickRe/spfx-msgraph-peoplesearch#10]
Profile pictures stop appearing after you enter a $select statement. Remove the $select statement and profile pictures reappear as you can see in the screenshots below. 
![No Select Statement - Profile Photo](https://user-images.githubusercontent.com/59395437/101817397-52c2eb00-3af0-11eb-8633-57bccbf11c1d.png)
![Select Statement - No Profile Photo](https://user-images.githubusercontent.com/59395437/101817399-535b8180-3af0-11eb-8bc5-fc83549b4eb3.png)

**Comment by YannickRe** [comment]
@kendalldTalon You did not provide the values for your $select statement, so it is just an assumptions. My guess is that you aren't selecting `id` in your $select statement. The code depends on this value for a user to fetch the user profile picture.

Could you confirm? Maybe add it in your $select statement and test?
If this is the case, I'll make a note to improve the code and add this in even when it isn't explicitly selected.

**Comment by kendalldTalon** [comment]
Adding id to the select fixed the issue.  Thanks.
