### ISSUE TITLE
spfx deployment

### ISSUE THREAD

**Issue by hendra-haliman** [YannickRe/spfx-msgraph-peoplesearch#12]
Hi,
When I deploy the app to app catalog, I did not see the permissions listed

![image](https://user-images.githubusercontent.com/20261280/102370163-5aeac100-3fef-11eb-86b3-d50abdcba716.png)

And I also did not have pending approval request in the API management

Do you know what cause it?Thanks

**Comment by YannickRe** [comment]
That's because the needed permissions aren't included in the package-solution.json file. I decided on using PnP PowerShell/CLI for Microsoft 365 to add the permissions: https://github.com/YannickRe/spfx-msgraph-peoplesearch#minimal-path-to-awesome

**Comment by hendra-haliman** [comment]
ok, thanks
