### ISSUE TITLE
How to modify the view layout as table?

### ISSUE THREAD

**Issue by hendra-haliman** [YannickRe/spfx-msgraph-peoplesearch#13]
Hi, I'm not familiar with react and I need your suggestion on how to modify the view layout as table?
Here is a sample picture of the picture
![image](https://user-images.githubusercontent.com/20261280/103173422-75ddf080-488d-11eb-9055-dfd3951e3fa3.png)

**Comment by YannickRe** [comment]
You will want to start with adjusting [src/services/TemplateService/TemplateService.ts](https://github.com/YannickRe/spfx-msgraph-peoplesearch/blob/master/src/services/TemplateService/TemplateService.ts) to add your new layout option, and potentially the configuration options it supports.
Additionally, you create your actual layout option underneath [src/components](https://github.com/YannickRe/spfx-msgraph-peoplesearch/tree/master/src/components) where the other layout-related code resides.

If you look in those two place you might be able to deduce the necessary changes you need to support your requirements.

Good luck!

**Comment by YannickRe** [comment]
@hendra-haliman Did this sufficiently help you? Can I close this issue?

**Comment by YannickRe** [comment]
Closed, because of inactivity.
