### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by MMAtHome** [YannickRe/spfx-msgraph-peoplesearch#15]
I see an error during npm install that says the code is looking for python2.  I'm pretty new to this so it may be a configuration issue.  If you have any pointers, that would be great or do you have a code branch that supports python3?

**Comment by YannickRe** [comment]
@MMAtHome Mind sharing the references you are seeing to Python?
This code does not use Python as a direct dependency, but it might be something that the SharePoint Framework uses under the covers.

**Comment by MMAtHome** [comment]
Thanks for responding so quickly.
I am pretty new to this so let me first tell you the steps I went through.
1. Cloned the repository to a local setup on my WIndows 10 machine
2. Opened a command window
3. Went to the directory containing the cloned repository
4. Ran npm install

It was during the npm install process that the error was generated.

I am thinking that this is probably a local environmental issue as I have
cloned another project this morning and attempted to run npm install on
that with pretty much the same error.
Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" %
sys.version_info[:3]
Everything after this point seems to be a problem from the above.

I'm happy to persevere with this but do you have a pre-built SharePoint
package that you could share with me?

**Comment by YannickRe** [comment]
Ok, it is starting to make sense to me. I "think" you don't have your computer set up for SharePoint Framework development yet, the information can be found on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment?WT.mc_id=M365-MVP-5003400
This will install some global prerequisites, after which you can run `npm install` in this project and you shouldn't be getting the Python error anymore.

It's a conscious decision to not release a pre-built package, as it infers some support from my side and there is no support. The only support I give is through this issue list when time permits me.
Also, second thing: with a pre-built package you aren't sure what you are putting in your environment and have to trust a bit that I do nothing malicious.

**Comment by MMAtHome** [comment]
Thank you very much for your comments and guidance.  I will get all the
prerequisites installed and let you know how it goes.
Best regards
Martin

**Comment by YannickRe** [comment]
Happy to help out in any way if you get stuck somewhere.

**Comment by MMAtHome** [comment]
Thanks again for your help.

**Comment by MMAtHome** [comment]
Hey Yannick,

I'm sorry to bother you again but I think I am really close to the
deployment working.  I have run all commands, deployed the package to my
tenant and run the relevant grant from m365 spo.  In SharePoint, I can add
the web part but I get the message below

AADSTS65001: The user or administrator has not consented to use the
application with ID '5675beda-b8a3-40de-a290-8cf4b3117be8' named
'SharePoint Online Client Extensibility Web Application Principal'. Send an
interactive authorization request for this user and resource. Trace ID:
1eaff9ae-9795-49ea-935b-25f5f3a6a600 Correlation ID:
16036007-5ffe-49f7-a890-f9658adf3570 Timestamp: 2021-02-16 17:28:08Z

I've located the app in AAD admin centre and given permissions as below to
a few users to see if I can get this to work but no luck

[image: image.png]

Any ideas would be appreciated.

Very best regards,

Martin

**Comment by MMAtHome** [comment]
Apologies - I found the issue - it seems that my m365 spo command did not
run correctly so I had to update the required permissions manually in AAD.
Thanks again
Martin

**Comment by YannickRe** [comment]
Good job!
