### ISSUE TITLE
Search Box missing when publishing

### ISSUE THREAD

**Issue by gmorken** [YannickRe/spfx-msgraph-peoplesearch#16]
The searchbox is not visible after publishing on a page even if I select it under search parameter options.

**Comment by YannickRe** [comment]
Someone had this issue before, mind checking if that thread resolves it for you: https://github.com/YannickRe/spfx-msgraph-peoplesearch/issues/9

If not, mind checking your console for JavaScript errors?

**Comment by YannickRe** [comment]
@gmorken I had some time to validate myself and a stupid code change introduced this issue. I believe I have fixed it now (if I haven't introduced any new issues), could you try the latest code?

**Comment by YannickRe** [comment]
Closed due to inactivity.

**Comment by gmorken** [comment]
> Closed due to inactivity.

sorry didnt have the time to test until now but it works!
