### ISSUE TITLE
Webpart not dynamically updating using Url Query String Parameter

### ISSUE THREAD

**Issue by artalvarado11** [YannickRe/spfx-msgraph-peoplesearch#18]
Hi,

I am using the PnP V4 Modern Search Box (Page 1) standalone on one page and passing the search query as query string parameter in the url to a different page in a new tab that contains another PnP Search Box and People Search webpart (Page 2). 
People Search (Page 2) is connected to the PnP Search Box (Page 2). PnP Search Box is configured to look at the Query String Parameter for search query.  The query is passed successfully however the People Search does not dynamically update. I tried refreshing and it appears that the People Search loads the correct results for a quick second but then restarts as if no query was passed.

**Comment by YannickRe** [comment]
@artalvarado11 I can reproduce. Haven't had time yet to investigate, and I am not sure if the root cause is within the Search Box web part or within my People Search Web Part.
I will try to take a closer look as soon as possible!

**Comment by YannickRe** [comment]
@artalvarado11 I'm sorry for the long wait but I pushed a code change that should fix this! If you get the code again and upload a new package (version 2.4.0.0) you shouldn't run into this again.
