### ISSUE TITLE
Connection to Vertical Webpart / Possibility of two Connections

### ISSUE THREAD

**Issue by xbernhard** [YannickRe/spfx-msgraph-peoplesearch#19]
<img width="249" alt="Capture1" src="https://user-images.githubusercontent.com/48352743/112339809-4c800580-8cc0-11eb-8493-b774ddd6cfc6.PNG">
<img width="245" alt="Capture2" src="https://user-images.githubusercontent.com/48352743/112339815-4d189c00-8cc0-11eb-93b0-2be0ab512d45.PNG">

Hello! Thank you for building this webpart, it is a great improvement as I was not satisfied with the modern-search solution either.

In my project I need to connect the people search webpart with two Things:
       > Page Environment -> Search -> query
       > PNP modern search vertical webpart (to show the people webpart only, when the "People"-tab on the vertical is selected)

Will there be the possibility to make two connections in the future? (I have tried to add it myself, but unfortunately without success.)

The connection to the Vertical webpart with the People Search webpart is different than how the connection with the Modern search results webpart to the Vertical webpart works. I have not found a way to configure "show only when the people tab is selected" as it works with the Modern Search results webpart. Is this a known problem? I have uploaded 2 Screenshots to show the issue. I am using modern search v4 webparts.

Thanks in advance for your efforts.

**Comment by YannickRe** [comment]
My web part is not related to the PnP Modern Search web parts and has no compatibility with the PnP Modern Search Vertical Web Part. It only supports the one connection to take a keyword query as input, but has no functionality to work with the Search Verticals web part, and thus cannot be configured like you ask.

**Comment by YannickRe** [comment]
Closed, since acknowledged but no plans to create this functionality.
