### ISSUE TITLE
Use substr in $filter query

### ISSUE THREAD

**Issue by YannickRe** [YannickRe/spfx-msgraph-peoplesearch#2]
I’m struggling with another problem of the webpart (or even more with the odata request). I would like to use substring of in the $filter parameter, but unfortunately it’s not working (-> invalid filter clause).

What I’m trying to to is:  $filter:  substring(‘OÖ’, department)
What’s working: $filter:  department eq ‘LD OÖ’

Do you have any information what I should use for using substring?

Thanks a lot and best regards,
Evelyn

**Comment by YannickRe** [comment]
Hi @hamev,

I split off your second question into a separate issue, it helps me manage the conversation.

As far as I can see it is not supported to use substr in $filter, while using Microsoft Graph. It's a bit difficult to figure out what is supported and what not, but it is basically [combining the generic info about $filter](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#filter-parameter) with [the properties of users that are supporting $filter](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#filter-parameter).

I hope you can figure out a filter that can work for you.

**Comment by naturelgass** [comment]
> I’m struggling with another problem of the webpart (or even more with the odata request). I would like to use substring of in the $filter parameter, but unfortunately it’s not working (-> invalid filter clause).
> 
> What I’m trying to to is: $filter: substring(‘OÖ’, department)
> What’s working: $filter: department eq ‘LD OÖ’
> 
> Do you have any information what I should use for using substring?
> 
> Thanks a lot and best regards,
> Evelyn

If found that the startswith string operator is supported, so you can search e.g. by the first letter like this: startswith(displayName,'A')
