### ISSUE TITLE
SearchService.ts return empty error message

### ISSUE THREAD

**Issue by KarolFilipKozlowski** [YannickRe/spfx-msgraph-peoplesearch#24]
I have a random bug, we have added You webpart at our Intranet site, and on Teams tab, on both pages/tabs site when user open SPO site and MS Teams first time (turn on the computer, lunch browser/ms teams) webpart showing only red bar without any error message. Refresh page or tab solving a problem. 
In my opinion, the problem is in connecting to MS Graph. somewhere in  src\services\SearchService\SearchService.ts at public async searchUsers(): Promise<PageCollection<ExtendedUser>>. 
I have no idea why my be a problem in our company infrastructure, not in w ms graph people search.

Because ist random and showing only on the first time when the page was the load I can not create steps to reproduce the behavior. I don't know why track issue or lunch some developer command in MS Teams

Any clue where I can start looking?
I have the same problem on v 2.3 and v2.5 with 1.0 or beta graphclient.

**Comment by YannickRe** [comment]
@KarolFilipKozlowski This is apparently a known issue with web parts that use SPFx aadServiceClient construct when embedded into Teams. In some cases it'll result in an error message on first load, and has to do with the version of MSAL that is used internally by SPFx. Currently there is no fix for that, I am sorry :(

**Comment by YannickRe** [comment]
Closing this. Can no longer reproduce this and in the meantime, this web part, the Teams mobile app, and SharePoint have gotten various updates. If this issue still persists, feel free to open a new issue.
