### ISSUE TITLE
Interactive authorization request required

### ISSUE THREAD

**Issue by YannickRe** [YannickRe/spfx-msgraph-peoplesearch#29]
![image](https://user-images.githubusercontent.com/58838385/127835495-bae89520-7ea5-497a-b3ea-6003f144f403.png)
I download → Install NPM → follow other steps to make package file→ then upload → find the above error
I did not do any changing in code

_Originally posted by @sirarif in https://github.com/YannickRe/spfx-msgraph-peoplesearch/issues/17#issuecomment-890861191_

**Comment by YannickRe** [comment]
@sirarif I moved this to a separate issue. I think you missed the part where you assign the necessary permissions through CLI for Microsoft 365 or PnP PowerShell:

Install the package:
- Add to AppCatalog and deploy
- Assign 'User.Read.All' delegated permissions to the 'SharePoint Online Client Extensibility Web Application Principal', with [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/) or [PnP PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/grant-pnptenantserviceprincipalpermission?view=sharepoint-ps)

### CLI for Microsoft 365
```
m365 login
m365 spo serviceprincipal grant add --resource 'Microsoft Graph' --scope 'User.Read.All'
```

### PnP PowerShell
```
Grant-PnPTenantServicePrincipalPermission -Scope "User.Read.All" -Resource "Microsoft Graph"
```

**Comment by YannickRe** [comment]
@sirarif Has this resolved your issue?

**Comment by YannickRe** [comment]
Given that you opened a new issue, I assume this one is resolved.

**Comment by sirarif** [comment]
Yes thanks a lot

**Comment by sirarif** [comment]
> @sirarif Has this resolved your issue?

Yes Sir, thanks a log
