### ISSUE TITLE
Live Persona Card not presented

### ISSUE THREAD

**Issue by marschallphilipp** [YannickRe/spfx-msgraph-peoplesearch#3]
Any additional step needed to get the Live Persona Card prompted when hovering or clicking a search result?
No LPC ist presented when I hover or click a search result.

**Comment by YannickRe** [comment]
Can you double check that the toggle is turned to on in the property pane of the web part?
Besides that, nothing is needed to have the LPC show up.

Of course, like stated, this is unsupported by Microsoft and they can make breaking changes without notifying us. Currently I still see the LPC working across my install base.

**Comment by marschallphilipp** [comment]
A typo within the $select statement fixed the issue....Thanks for the quick response!
