### ISSUE TITLE
Problem with VIVA in Teams Desktop App

### ISSUE THREAD

**Issue by aknueppel** [YannickRe/spfx-msgraph-peoplesearch#35]
We host a modern SharePoint site in SharePoint Online with your Peoplesearch web part.
There is no problem when I use a browser to view the sharepoint site.
We have integrated the site with the new MS VIVA app into teams.
And there is the problem. Teams Web shows the web part, but the Teams desktop app (Windows) often shows a red bar with an x at the beginning. Most of the time when I hit update it works.

I imagine it could be a timing issue.
When Teams opens, there is a lot of work to do in the background and there is a delay in displaying the web part.
This would also be supported by the fact that a PC that is very slow does not manage to display the web part in Teams (desktop app), but in the browser (teams.microsoft.com) it does.

This is what it looks like in the Teams desktop app

![image](https://user-images.githubusercontent.com/83067423/132646576-bfe3a0d5-7d8b-4911-bb17-a1a542fa1e63.png)

**Comment by YannickRe** [comment]
Closing this. Can no longer reproduce this and in the meantime, this web part, the Teams mobile app, and SharePoint have gotten various updates. If this issue still persists, feel free to open a new issue.
