### ISSUE TITLE
People Search default value

### ISSUE THREAD

**Issue by rajeshb4** [YannickRe/spfx-msgraph-peoplesearch#43]
Hi Yannick,

I am trying to use your webpart to implement people search page. I have configured the searchbox option and selected show blank if no result radio button. The search results come up fine when searched through search box but if I click on close button next to search term in the search box all the people profile from entire tenant shows up instead of blank. I was expecting to see nil results when the search term is cleared.

Do let me know your thoughts on this.

**Comment by YannickRe** [comment]
@rajeshb4 that sounds like a bug. I can recreate the issue, and this should not be the case.
Unfortunately it doesn't seem to be an easy fix, and I'm not sure when I will have time to address this 😟

**Comment by rajeshb4** [comment]
Ah thats sad. I'll keep an eye on this repo if ever fix is deployed. Cool work so far. :)
