### ISSUE TITLE
 Token request previously failed

### ISSUE THREAD

**Issue by Spruit33** [YannickRe/spfx-msgraph-peoplesearch#65]
Hi, 

I've added the app to our SharePoint Online with only Azure AD, that is working fine. 

Now I've also placed this app to a SharePoint connect with Azure AD and also an on premise AD.
When placing the app I get the notification "Token request previously failed"

Do you've any idea how to solve this problem? 
I've googled, but didn't find anything so far. 

I hope you can help me.

**Comment by Spruit33** [comment]
This problem is solved with granting access 
Grant-PnPTenantServicePrincipalPermission -Scope "User.Read.All" -Resource "Microsoft Graph"

**Comment by YannickRe** [comment]
Glad you resolved it, thanks for letting me know!

**Comment by ChristianOtte** [comment]
Hi

I've been using this amazing people-search, but from today it suddently return this error "Token request previously failed"

I've tried this command Grant-PnPTenantServicePrincipalPermission -Scope "User.Read.All" -Resource "Microsoft Graph" but stil does not work.

The SharePoint Online Client Extensibility Web Application Principal got user.read.all
Tried removing the webparts from my app catalog and uploaded the newest version, not luck on that.

Also tested in a different test environment, but this issue persists

Do you have a suggestion what might go wrong here?
