### ISSUE TITLE
Live Persona Card no longer working

### ISSUE THREAD

**Issue by SleepyBandit** [YannickRe/spfx-msgraph-peoplesearch#7]
Had this excellent web part up and working without issue. The live person card feature worked great and we have not done any configuration changes since.

Some point in the last week the live persona card stopped working. In the console I see a GET call to delve.office.com/api/v1/configuration/SPPeopleWebPart/en-US that is failing due to NET:: ERR_CERT_COMMON_NAME_INVALID

I don't know if that is the cause or something else. Is this still working for anyone else?

**Comment by YannickRe** [comment]
I'm currently not seeing any issues on the installations I have going on.  My call goes out to https://loki.delve.office.com/api/v1/configuration/SPPeopleWebPart/en-US and it returns 200.
As you know, this is not officially supported so the integration with the LPC can break at any point.

**Comment by SleepyBandit** [comment]
Sorry @YannickRe I should have looked closer. The call is going to a GCC version of Delve.
[https://loki.delve-gcc.office.com/api/v1/configuration/SPPeopleWebPart/en-US](https://loki.delve-gcc.office.com/api/v1/configuration/SPPeopleWebPart/en-US)

When I go to that link I see the cert error while the regular delve one doesn't.

**Comment by YannickRe** [comment]
No worries. Do you have the same issue when the LPC is triggered from a "native" location, like a person field in SharePoint list or the standard People web part?
If so, I suggest you log a ticket with Microsoft.

**Comment by YannickRe** [comment]
@SleepyBandit Has this been resolved for you?

**Comment by SleepyBandit** [comment]
> @SleepyBandit Has this been resolved for you?

Yes, just got word from Microsoft earlier this week that this was a cert error on their end. Thanks for the help 👍
