### ISSUE TITLE
Card does not load correctly if selected person is guest

### ISSUE THREAD

**Issue by corriganc** [YannickRe/spfx-msgraph-peoplesearch#77]
When the People Search picks up Guest users, the list view shows all of the correct information - display name, job title, email, phone - exactly as we've selected:
<img width="564" alt="image" src="https://github.com/YannickRe/spfx-msgraph-peoplesearch/assets/51030709/9248d456-b326-40f5-8596-79cc0c11ef25">

However, upon clicking a Guest users' card, it does not load properly like a standard member users'. Instead, it shows the display name as the UPN for the Guest, and no other information is loaded:
<img width="612" alt="image" src="https://github.com/YannickRe/spfx-msgraph-peoplesearch/assets/51030709/3e17a468-7d51-49f7-ac0d-ed93149bd1c0">

**Comment by murchelon** [comment]
I belive that guest users dont have an entry in User Profile, and maybe thats why it doesnt show the correct information. Can anyone confirm that ?

**Comment by YannickRe** [comment]
This does work on an out of the box SharePoint where guests show up in the Created By or Modified By of a list item. Probably the "input" for the LPC is expected to be different than what I am currently feeding it.
I'll keep the issue open until I have time to fix it.

**Comment by YannickRe** [comment]
This has been fixed in the latest code base.
