### ISSUE TITLE
Search functions

### ISSUE THREAD

**Issue by Spruit3** [YannickRe/spfx-msgraph-peoplesearch#78]
Hi, 

When you search on a job title with an "&" in it, it doesn't work. Is this possible to make this work? 
Also the search term has to start with the beginning of the name or whatever you looking for. Is it possible to search on a term that contains the job title? 
By example, the job title is "Servicedesk Engineer". If you use the search term Engineer, you wouldn't find anything. 
It would be nice if the people with the job titlte Servicedesk Engineer will appear.

**Comment by YannickRe** [comment]
1. Seems to be a bug, it also has been reported in #75 . I will keep this ticket open until I have time to resolve it.
2. JobTitle is not a proper that supports fulltext search, unfortunately this is a limitation of Microsoft Graph

**Comment by YannickRe** [comment]
I made a bypass because it's Microsoft Graph that doesn't allow an & in the query, not much I can do about it. I now remove the ampersand from the query so the web part doesn't end in a broken state.
