### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by guptar1** [YannickRe/spfx-msgraph-peoplesearch#8]
Hi Yannick

This is an excellent webpart. Thanks for sharing. I have manged to install and embed the webpart to my SPO site but would like to do the following:
1) Hide Linkedin from LPC
2) Connect the webpart to a refiner webpart

Any suggestions how this can be achieved?

Many Thanks & Regards

**Comment by YannickRe** [comment]
Hi @guptar1 ,

Thank you for the feedback. With regards to your questions:

1. It is an out of the box card, not sure you can disable this. Maybe try the following => https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/linkedin-integration
2. I have not build any refiner connectivity into the web part, and I don't have any plans for it. You might be able to use Dynamic Data functionality in SPFx to expose this functionality to a custom refiner web part. You'll have to fork my code and build this yourself.

Kind regards.

**Comment by guptar1** [comment]
> Hi @guptar1 ,
> 
> Thank you for the feedback. With regards to your questions:
> 
> 1. It is an out of the box card, not sure you can disable this. Maybe try the following => https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/linkedin-integration
> 2. I have not build any refiner connectivity into the web part, and I don't have any plans for it. You might be able to use Dynamic Data functionality in SPFx to expose this functionality to a custom refiner web part. You'll have to fork my code and build this yourself.
> 
> Kind regards.

Many thanks for your answer Yannick. I will try to play around with the code. Thanks again for this awesome webpart.
