### ISSUE TITLE
User Card Display: Delay between User Profile Update and Populate to User Card

### ISSUE THREAD

**Issue by Id10tSupport** [YannickRe/spfx-msgraph-peoplesearch#80]
**Describe the bug**
I have noticed a delay with the user card displaying About Me details, about 24-48 hours after update in UPS.  Usually happens for profiles that already have About Me text and are getting an update.

**To Reproduce**
Enter About Me details into user's profile.
Allow enough time for it to appear on the User Card (Contact tab, About Me section)
Return to user profile in UPS and update text of About Me field and save profile.
Refresh page and re-open user profile card
 -- finding thatthe text has not updated and will take up to 48 hours (if not longer) to reflect the changes

**Expected behavior**
Expectation is that the updated text would appear shortly after the profile About Me field has been updated and save within UPS.

**Comment by YannickRe** [comment]
Pretty sure this has nothing to do with the web part. This web part fetches the data available in the Graph, if it's not updated there then there is nothing I can do about it. Second: the persona card that shows on popup is a reused MS component. There is nothing I control about it either. You'll probably see the same results on the out of the box People webpart.
