### ISSUE TITLE
Unable to display business phone

### ISSUE THREAD

**Issue by corriganc** [YannickRe/spfx-msgraph-peoplesearch#83]
When selecting the persona fields, I am unable to get the business phone to display. I've tried 'phone', 'telephone', 'businessPhone', 'business' etc. but all return a blank. 'mobilePhone' works fine.

Can you confirm what the correct field name for business phone is please?

**Comment by YannickRe** [comment]
You can find all field names in the Graph documentation: https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

In your case, it's "businessPhones".
