### ISSUE TITLE
Live Persona Card: Full information only shown for my user

### ISSUE THREAD

**Issue by haksuman** [YannickRe/spfx-msgraph-peoplesearch#85]
**Description of bug**
People search webpart works well on my tenant site but when I deployed to a specific project site, there is a strange error. Live persona card only shows full information about me, although the other users have also relevant data, live persona card only shows mail for them. When another account logs in then it can only full information about itself in same manner and cannot see the others full information. 

Me on live persona card:
![image](https://github.com/YannickRe/spfx-msgraph-peoplesearch/assets/51818946/029cdcfb-d273-4444-81bc-c101f5fcf192)

Other users on persona card:
![image](https://github.com/YannickRe/spfx-msgraph-peoplesearch/assets/51818946/ccc8e480-b133-4e6e-93ca-efbb9ce22d38)

I have already checked the code for live persona card render, but the it gets the same props for me and different user, but still renders other users with missing information. Also, search-bar result for other user live persona card in this sharepoint site works just fine. 

Site search result for same other user:
![image](https://github.com/YannickRe/spfx-msgraph-peoplesearch/assets/51818946/1418a982-2509-41c3-9b7e-7747f7aa2fba)

**To Reproduce**
1. Go to hover a person card and then click on it. 
2. See the results information for person in live persona card content. 

**Expected behavior**
It should not only show me all information related my user in live persona card but also needs to show other users' information once I clicked to their persona card to open up live persona card. 

**Additional context**
As far as I understood, this bug does not occur every sharepoint site, I really does not understand why it happens and also tried to change the live persona component id with default search live persona card id but i still get the same results.

**Comment by YannickRe** [comment]
I'm very sorry, but I cannot replicate this behavior...
